spring:
  application:
    name: expand-apis-test-task
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: RedDeadRedemption2
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
